# Generated by Django 4.2.6 on 2023-10-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='day_started',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='minutes_tutored',
            field=models.IntegerField(default=0),
        ),
    ]
