# Generated by Django 4.2.6 on 2023-10-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0003_major_alter_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
